import { CategoryFilter } from '@app/interfaces/filters';

export const categoryList: Array<CategoryFilter> = [
  {
    name: "Social",
    group: [
      "Health",
      "Marriage",
      "Education",
      "Mentorship",
      "Retirement",
      "Housing",
      "Rental Flats",
      "Family",
      "Gender",
      "Elderly",
      "Youth",
      "Youth At Risk",
      "Pre-School",
      "Race",
      "Language",
      "Science",
      "Art",
      "Sports",
      "Poverty",
      "Inequality",
    ],
  },
  {
    name: "Environment",
    group: ["Recycling", "Green", "Water", "Waste", "Food", "Growing"],
  },
  {
    name: "Economical",
    group: [
      "Finance",
      "Jobs",
      "Wage",
      "Upskill",
      "Technology ",
      "IT",
      "IoT 4.0",
      "Information",
      "Automation",
      "Online",
      "Digitalization",
    ],
  },
  {
    name: "Others",
    group: ["Productivity", "Innovation", "Research", "Manpower", "Design"],
  },
];

export const categoryListCustom: Array<CategoryFilter> = [
  {
    name: "Social",
    group: [
      "Health",
      "Marriage",
      "Education",
      "Mentorship",
      "Retirement",
      "Housing",
      "Rental Flats",
      "Family",
      "Gender",
      "Elderly",
      "Youth",
      "Youth At Risk",
      "Pre-School",
      "Race",
      "Language",
      "Science",
      "Art",
      "Sports",
      "Poverty",
      "Inequality",
    ],
  },
  {
    name: "Environment",
    group: ["Recycling", "Green", "Water", "Waste", "Food", "Growing"],
  },
  {
    name: "Economical",
    group: [
      "Finance",
      "Jobs",
      "Wage",
      "Upskill",
      "Technology",
      "IT",
      "IoT 4.0",
      "Information",
      "Automation",
      "Online",
      "Digitalization",
    ],
  },
  {
    name: "Others",
    group: ["Productivity", "Innovation", "Research", "Manpower", "Design"],
  },
  {
    name: "Customise",
    group: ["Create a Category"],
  },
];