export const locationList: Array<Object> = [
    {
      name: "North",
      group: [
        "Admiralty",
        "Kranji",
        "Woodlands",
        "Sembawang",
        "Yishun",
        "Yio Chu Kang",
        "Seletar",
        "Sengkang",
      ],
    },
    {
      name: "South",
      group: [
        "Holland",
        "Queenstown",
        "Bukit Merah",
        "Telok Blangah",
        "Pasir Panjang",
        "Sentosa",
        "Bukit Timah",
        "Newton",
        "Orchard",
        "City",
        "Marina South",
      ],
    },
    {
      name: "East",
      group: [
        "Serangoon",
        "Punggol",
        "Hougang",
        "Tampines",
        "Pasir Ris",
        "Loyang",
        "Simei",
        "Kallang",
        "Katong",
        "East Coast",
        "Macpherson",
        "Bedok",
        "Pulau Ubin",
        "Pulau Tekong",
      ],
    },
    {
      name: "West",
      group: [
        "Lim Chu Kang",
        "Choa Chu Kang",
        "Bukit Panjang",
        "Tuas",
        "Jurong East",
        "Jurong West",
        "Jurong Industrial Estate",
        "Bukit Batok",
        "Hillview",
        "West Coast",
        "Clementi",
      ],
    },
    {
      name: "Central",
      group: [
        "Thomson",
        "Marymount",
        "Sin Ming",
        "Ang Mo Kio",
        "Bishan",
        "Serangoon Gardens",
        "MacRitchie",
        "Toa Payoh",
      ],
    },
];
